version: "3.5"

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "qwerty"
  app:
    build: .
    command: ./cmd/app
    environment:
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - 8080:8080
    depends_on:
      - postgres
